; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
	git@github.com:SolidGeek/VescUart.git
	git@github.com:PaulStoffregen/XPT2046_Touchscreen.git
	git@github.com:cyberp/AT24Cx.git
	adafruit/RTClib@^2.1.4
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/Adafruit BMP280 Library@^3.0.0
	bolderflight/Bolder Flight Systems MPU9250@^1.0.2
	milesburton/DallasTemperature@^4.0.6
	slashdevin/NeoGPS@^4.2.9
	greiman/SdFat@^2.3.1
