; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = -std=gnu++17 -O2 -DDEBUG_LOGGING
build_unflags = -std=gnu++11 -Os
monitor_speed = 500000
lib_deps =
	git@github.com:SolidGeek/VescUart.git
	git@github.com:PaulStoffregen/XPT2046_Touchscreen.git
	git@github.com:bolderflight/invensense-imu.git
	git@github.com:ivanseidel/LinkedList.git
	git@github.com:SlashDevin/NeoHWSerial.git
	slashdevin/NeoGPS@^4.2.9
	adafruit/RTClib@^2.1.4
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/Adafruit BMP280 Library@^3.0.0
	milesburton/DallasTemperature@^4.0.6
	greiman/SdFat@^2.3.1
	paulstoffregen/OneWire@^2.3.8
	paulstoffregen/TimerOne@^1.2
	sparkfun/SparkFun External EEPROM Arduino Library@^3.2.13
	moononournation/GFX Library for Arduino@^1.6.7
extra_scripts = pre:scripts/patch_neogps.py
